sudo: false
language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - ~/.npm
notifications:
  email: false
  slack: react-dip:Z6Jf26OaXQgan2qcilZz3NjY
install: npm install
after_success: kcd-scripts travis-after-success
branches:
  only: master